---
# tasks file for WordPress
- name: Downloading & unarchiving WordPress Package
  unarchive:
    src: http://wordpress.org/latest.tar.gz
    dest: /var/www/html
    remote_src: yes
- name: moving the sample file into wp-config.php
  command: mv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
- name: Updating WordPress config file
  lineinfile:
    dest: /var/www/html/wordpress/wp-config.php
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', 'tables');"}
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', 'unknown');"}
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', 'qwerty');"}
    - {'regexp': "define\\('DB_HOST', '(.)+'\\);", 'line': "define('DB_HOST', '192.168.153.32');"}
  sudo: yes
